import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterAll, describe, expect, it } from 'vitest';

import { bundleConfigSource, entrySource, newestMtime, sdkAliases } from './guestBuild.js';
import { toPosix } from './paths.js';

const scratch = toPosix(mkdtempSync(join(tmpdir(), 'aos-cli-')));

afterAll(() => {
  rmSync(scratch, { recursive: true, force: true });
});

describe('entrySource', () => {
  it('imports the SDK factory and the game by relative specifier', () => {
    const source = entrySource(
      'F:/games/my-fps/.gameable',
      'F:/games/my-fps/node_modules/@gameable/sdk/src/wit/entry.ts',
      'F:/games/my-fps/src/game.ts',
    );
    expect(source).toContain(
      "import { createGuestExports } from '../node_modules/@gameable/sdk/src/wit/entry';",
    );
    expect(source).toContain("import definition from '../src/game';");
    expect(source).toContain('export const game = createGuestExports(definition);');
  });

  it('never emits a backslash, whatever it is given', () => {
    const source = entrySource(
      'F:\\games\\my-fps\\.gameable',
      'F:\\repo\\packages\\sdk\\src\\wit\\entry.ts',
      'F:\\games\\my-fps\\src\\game.ts',
    );
    expect(source).not.toContain('\\');
  });

  it('drops the .ts extension, because rolldown adds it back', () => {
    const source = entrySource('F:/g/.gameable', 'F:/g/sdk/entry.ts', 'F:/g/src/game.ts');
    expect(source).not.toContain(".ts'");
  });

  it('marks itself generated', () => {
    expect(entrySource('F:/g/.gameable', 'F:/g/e.ts', 'F:/g/src/game.ts')).toContain(
      'GENERATED by @gameable/cli',
    );
  });
});

describe('sdkAliases', () => {
  it('maps every gameable-source export onto its source file, longest first', () => {
    const dir = `${scratch}/fake-sdk`;
    rmSync(dir, { recursive: true, force: true });
    mkdirSync(dir, { recursive: true });
    writeFileSync(
      `${dir}/package.json`,
      JSON.stringify({
        exports: {
          '.': { 'gameable-source': './src/index.ts', import: './dist/index.js' },
          './prelude': { 'gameable-source': './src/prelude.ts', import: './dist/prelude.js' },
          './keycodes': { 'gameable-source': './src/keycodes.ts', import: './dist/keycodes.js' },
          './wit/entry': './src/wit/entry.ts',
          './package.json': './package.json',
        },
      }),
      'utf8',
    );

    const aliases = sdkAliases(dir);
    const keys = Object.keys(aliases);

    expect(aliases.gameable).toBe(`${dir}/src/index.ts`);
    expect(aliases['gameable/sdk/prelude']).toBe(`${dir}/src/prelude.ts`);
    expect(aliases['@gameable/sdk']).toBe(`${dir}/src/index.ts`);
    expect(aliases['@gameable/sdk/prelude']).toBe(`${dir}/src/prelude.ts`);
    expect(aliases['@gameable/sdk/wit/entry']).toBe(`${dir}/src/wit/entry.ts`);
    // package.json is not TypeScript and must not be aliased.
    expect(keys).not.toContain('@gameable/sdk/package.json');
    // The bare name must come last, so subpaths win.
    expect(keys.indexOf('gameable')).toBe(keys.length - 1);
  });
});

describe('bundleConfigSource', () => {
  it('emits a rolldown resolve.alias record', () => {
    const source = bundleConfigSource({
      '@gameable/sdk/prelude': 'F:/repo/packages/sdk/src/prelude.ts',
      '@gameable/sdk': 'F:/repo/packages/sdk/src/index.ts',
    });
    expect(source).toContain('resolve:');
    expect(source).toContain("'@gameable/sdk/prelude': 'F:/repo/packages/sdk/src/prelude.ts',");
    expect(source).not.toContain('\\');
    expect(source.indexOf('/prelude')).toBeLessThan(source.lastIndexOf("'@gameable/sdk'"));
  });
});

describe('newestMtime', () => {
  it('returns 0 for a path that is not there', () => {
    expect(newestMtime(`${scratch}/nope`)).toBe(0);
  });

  it('reports a file mtime', () => {
    const file = `${scratch}/a.txt`;
    writeFileSync(file, 'x', 'utf8');
    expect(newestMtime(file)).toBeGreaterThan(0);
  });
});
