#!/usr/bin/env node
/**
 * Compile every `.wgsl` under `src/` into `src/generated/<name>.wgsl.ts`.
 *
 * WHY THIS EXISTS. The POC imports shaders as `./x.wgsl?raw`, which is a Vite
 * transform: it fails under `tsc`, under node's test runner and under `tsdown`,
 * which is exactly why the POC has to lazy-import every module that touches a
 * shader and why its shader maths cannot be unit-tested. Generating a plain
 * TypeScript module instead makes a shader an ordinary import with no bundler
 * involvement, so `test/wgsl-syntax.test.ts` can read the shipped string.
 *
 * `// #include "name.wgsl"` is resolved here by STRING CONCATENATION, which is how
 * the LBS routine is shared between `rig/orl/wgsl/orl_deform.wgsl` and
 * `rig/gnm/wgsl/gnm_blend.wgsl`. WGSL has no preprocessor and the two rigs must
 * not carry two copies of the same skinning loop: they would drift, and a drift in
 * LBS is a face that is subtly in the wrong place with no error anywhere.
 * Includes are resolved once, depth-first, and a file is inlined at most once per
 * shader.
 *
 * Output is gitignored (every package's `src/generated/`), so this runs in `prebuild`
 * and `pretest`. Usage: `node scripts/wgsl-to-ts.mjs`.
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const PACKAGE_ROOT = fileURLToPath(new URL('../', import.meta.url));
const SRC = join(PACKAGE_ROOT, 'src');
const OUT = join(SRC, 'generated');

/**
 * Every `.wgsl` file under `dir`, recursively.
 *
 * @param {string} dir Absolute directory.
 * @returns {string[]} Absolute paths, sorted for deterministic output.
 */
function findShaders(dir) {
  /** @type {string[]} */
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
    a.name < b.name ? -1 : 1,
  )) {
    if (entry.name === 'generated' || entry.name === 'node_modules') continue;
    const abs = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...findShaders(abs));
    else if (entry.name.endsWith('.wgsl')) out.push(abs);
  }
  return out;
}

/**
 * `lift_pass2_cov.wgsl` -> `liftPass2Cov`. Basenames are unique across the
 * package, which the caller asserts.
 *
 * @param {string} file Shader filename, with extension.
 * @returns {string} camelCase export name stem.
 */
function stemOf(file) {
  return file
    .replace(/\.wgsl$/, '')
    .split(/[_-]/)
    .map((part, index) => (index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join('');
}

const INCLUDE = /^[ \t]*\/\/[ \t]*#include[ \t]+"([^"]+)"[ \t]*$/gm;

/**
 * Resolve `// #include "x.wgsl"` directives against `byName`.
 *
 * @param {string} source Shader text.
 * @param {Map<string, string>} byName Basename -> raw text.
 * @param {string} where The including file, for error messages.
 * @param {Set<string>} seen Already-inlined basenames, to keep the expansion finite.
 * @returns {string} The expanded shader.
 */
function expand(source, byName, where, seen = new Set()) {
  return source.replace(INCLUDE, (_line, name) => {
    if (seen.has(name)) return `// (#include "${name}" already inlined)`;
    const included = byName.get(name);
    if (included === undefined) {
      throw new Error(`${where}: #include "${name}" does not name a .wgsl file in src/`);
    }
    seen.add(name);
    const body = expand(included, byName, name, seen);
    return `// ---- begin #include "${name}" ----\n${body}\n// ---- end #include "${name}" ----`;
  });
}

/**
 * Escape a shader for a TypeScript template literal.
 *
 * @param {string} source Shader text.
 * @returns {string} Escaped text safe inside backticks.
 */
function escapeTemplate(source) {
  return source.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

/** Generate every module. */
function main() {
  const shaders = findShaders(SRC);
  /** @type {Map<string, string>} */
  const byName = new Map();
  /** @type {Map<string, string>} */
  const sourceOf = new Map();
  for (const abs of shaders) {
    const name = abs.split(/[\\/]/).pop();
    if (byName.has(name)) {
      throw new Error(`wgsl-to-ts: two shaders are both named ${name}; basenames must be unique`);
    }
    byName.set(name, readFileSync(abs, 'utf8'));
    sourceOf.set(name, relative(PACKAGE_ROOT, abs).replaceAll('\\', '/'));
  }

  rmSync(OUT, { recursive: true, force: true });
  mkdirSync(OUT, { recursive: true });

  /** @type {string[]} */
  const index = [];
  for (const [name, raw] of [...byName].sort(([a], [b]) => (a < b ? -1 : 1))) {
    const stem = stemOf(name);
    const expanded = expand(raw, byName, name);
    const module = [
      '// GENERATED by scripts/wgsl-to-ts.mjs — do not edit.',
      `// Source: ${sourceOf.get(name)}`,
      '',
      `/** WGSL source of \`${name}\`, with every \`#include\` already inlined. */`,
      `export const ${stem}Wgsl = \`${escapeTemplate(expanded)}\`;`,
      '',
    ].join('\n');
    writeFileSync(join(OUT, `${name}.ts`), module, 'utf8');
    // `.js` in the specifier, `.ts` on disk: the repo compiles ESM with explicit
    // extensions, so a generated module must import the way a hand-written one does.
    index.push(`export { ${stem}Wgsl } from './${name}.js';`);
  }

  writeFileSync(
    join(OUT, 'index.ts'),
    ['// GENERATED by scripts/wgsl-to-ts.mjs — do not edit.', '', ...index, ''].join('\n'),
    'utf8',
  );
  const dest = relative(PACKAGE_ROOT, OUT).replaceAll('\\', '/');
  console.log(`wgsl-to-ts: ${byName.size} shader(s) -> ${dest}/`);
}

main();
