#!/usr/bin/env node
/**
 * Writes `src/<file>.ts` and the `exports` map of `package.json` from
 * `entries.mjs`.
 *
 *   node scripts/gen-entries.mjs          # write
 *   node scripts/gen-entries.mjs --check  # fail if anything is out of date,
 *                                         # or a workspace export is unmapped
 */
import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { ENTRIES, PRIVATE_EXPORTS } from '../entries.mjs';

const PKG = join(dirname(fileURLToPath(import.meta.url)), '..');
const PACKAGES = join(PKG, '..');
const check = process.argv.includes('--check');
const problems = [];

function shim(entry) {
  return [
    '// GENERATED by scripts/gen-entries.mjs from entries.mjs — do not edit.',
    `export * from '${entry.from}';`,
    '',
  ].join('\n');
}

function exportsMap() {
  const map = {};
  for (const e of ENTRIES) {
    map[e.subpath] = {
      'gameable-source': `./src/${e.file}.ts`,
      types: `./dist/${e.file}.d.ts`,
      import: `./dist/${e.file}.js`,
    };
  }
  map['./assets/*'] = './assets/*';
  map['./wit/*.wit'] = './wit/*.wit';
  map['./package.json'] = './package.json';
  return map;
}

function write(path, text) {
  const current = existsSync(path) ? readFileSync(path, 'utf8') : undefined;
  if (current === text) return;
  if (check) {
    problems.push(`${path} is out of date`);
    return;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, text);
}

for (const e of ENTRIES) write(join(PKG, 'src', `${e.file}.ts`), shim(e));

const pkgPath = join(PKG, 'package.json');
const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
pkg.exports = exportsMap();
write(pkgPath, JSON.stringify(pkg, null, 2) + '\n');

// Every export of every workspace package is public through some subpath, or
// listed as deliberately private.
const mapped = new Set([...ENTRIES.map((e) => e.from), ...PRIVATE_EXPORTS]);
for (const dir of readdirSync(PACKAGES)) {
  const manifest = join(PACKAGES, dir, 'package.json');
  if (dir === 'gameable' || dir === 'create-gameable' || !existsSync(manifest)) continue;
  const { name, exports = {} } = JSON.parse(readFileSync(manifest, 'utf8'));
  for (const subpath of Object.keys(exports)) {
    const specifier = subpath === '.' ? name : `${name}${subpath.slice(1)}`;
    if (!mapped.has(specifier)) problems.push(`${specifier} has no row in entries.mjs`);
  }
}

if (problems.length > 0) {
  console.error(problems.join('\n'));
  console.error(
    'Run `npm run gen -w packages/gameable`, and add a row to entries.mjs for a new export.',
  );
  process.exit(1);
}
if (!check) console.log(`wrote ${ENTRIES.length} entries`);
