import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { defineConfig, type DefaultTheme } from 'vitepress';
import { publishLlms } from '../../tools/docs/publish-llms.mjs';

/**
 * The sidebar is built from the filesystem, never from a hand-maintained list.
 *
 * Recipes and API pages arrive in batches — a recipe set lands with a
 * template, `docs/api/` is regenerated by TypeDoc on every build — and a literal
 * sidebar goes stale the moment one of them lands. Everything below reads the
 * directory and takes each entry's title from its first level-1 heading.
 */

/** Absolute path to `docs/`. */
const DOCS = fileURLToPath(new URL('../', import.meta.url));

// Run for both dev and production, including direct VitePress invocations.
publishLlms(join(DOCS, 'public'));

/**
 * Sorted markdown filenames in a `docs/` subdirectory.
 *
 * @param dir Path relative to `docs/`.
 * @param skip Basenames to leave out, typically the directory's own index.
 * @returns Filenames, ascending.
 */
function mdFiles(dir: string, skip: string[] = []): string[] {
  const abs = join(DOCS, dir);
  if (!existsSync(abs)) return [];
  return readdirSync(abs)
    .filter((f) => f.endsWith('.md') && !skip.includes(f))
    .sort((a, b) => (a < b ? -1 : 1));
}

/**
 * The first level-1 heading of a markdown file, or a title-cased filename.
 *
 * @param dir Path relative to `docs/`.
 * @param file Filename inside `dir`.
 * @returns The page title.
 */
function titleOf(dir: string, file: string): string {
  const abs = join(DOCS, dir, file);
  const text = readFileSync(abs, 'utf8').replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n/, '');
  const heading = /^#\s+(.+?)\s*$/m.exec(text);
  if (heading) return heading[1];
  return basename(file, '.md')
    .replace(/^\d+-/, '')
    .replaceAll('-', ' ')
    .replace(/^./, (c) => c.toUpperCase());
}

/**
 * One sidebar item per markdown file in a directory.
 *
 * @param dir Path relative to `docs/`.
 * @param skip Basenames to leave out.
 * @returns Sidebar items, in filename order.
 */
function itemsOf(dir: string, skip: string[] = []): DefaultTheme.SidebarItem[] {
  return mdFiles(dir, skip).map((f) => ({
    text: titleOf(dir, f),
    link: `/${dir}/${basename(f, '.md')}`,
  }));
}

/**
 * Concept pages, in reading order: the ones a newcomer needs first, then
 * whatever else the directory holds, alphabetically. New concept pages appear
 * without touching this file.
 */
const CONCEPT_ORDER = [
  'engine-loop.md',
  'modules.md',
  'assets.md',
  'wasm-boundary.md',
  'ecs.md',
  'splats.md',
  'characters.md',
  'animation.md',
  'physics.md',
];

/**
 * The Concepts section.
 *
 * @returns Sidebar items, overview first.
 */
function conceptItems(): DefaultTheme.SidebarItem[] {
  const present = mdFiles('concepts', ['index.md', 'README.md']);
  const known = CONCEPT_ORDER.filter((f) => present.includes(f));
  const rest = present.filter((f) => !CONCEPT_ORDER.includes(f));
  return [
    { text: 'Overview', link: '/concepts/' },
    ...[...known, ...rest].map((f) => ({
      text: titleOf('concepts', f),
      link: `/concepts/${basename(f, '.md')}`,
    })),
  ];
}

/**
 * The Recipes section: every file in `docs/recipes/`, titled by its first
 * heading and sorted by that title rather than by filename, because a reader
 * scans the words and not the verb-noun slug.
 *
 * @returns Sidebar items, the listing first.
 */
function recipeItems(): DefaultTheme.SidebarItem[] {
  const items = mdFiles('recipes', ['index.md', 'README.md'])
    .map((f) => ({ text: titleOf('recipes', f), link: `/recipes/${basename(f, '.md')}` }))
    .sort((a, b) => a.text.localeCompare(b.text, 'en'));
  return [{ text: 'All recipes', link: '/recipes/' }, ...items];
}

/**
 * The generated API reference. `docs/api/` is TypeDoc output: gitignored,
 * written by `npm run docs:api`, one flat file per package named
 * `@gameable.<pkg>.md`.
 *
 * @returns Sidebar items, one per package.
 */
function apiItems(): DefaultTheme.SidebarItem[] {
  const items = mdFiles('api', ['index.md']).map((f) => {
    const slug = basename(f, '.md');
    return { text: slug.replace('@gameable.', '@gameable/'), link: `/api/${slug}` };
  });
  return [{ text: 'All packages', link: '/api/' }, ...items];
}

if (!existsSync(join(DOCS, 'api/index.md'))) {
  throw new Error(
    'docs/api/ is missing. It is generated and gitignored — run `npm run docs:api` before `npm run docs:build` or `npm run docs:dev`.',
  );
}

/**
 * A dev-server middleware that lets `/play/<game>/` reach the game.
 *
 * `npm run docs:games` builds each playable example into
 * `docs/public/play/<game>/`, and VitePress serves `docs/public/` as-is. A
 * static host maps the directory URL onto its `index.html`; Vite's public-file
 * middleware does not, so without this the dev server would answer `/play/fps/`
 * with the docs 404 page while `docs:build` output works. It rewrites the URL
 * and lets Vite serve the file.
 *
 * @returns A Vite plugin with only a `configureServer` hook.
 */
function playIndexPlugin() {
  return {
    name: 'gameable-play-index',
    configureServer(server: {
      middlewares: {
        use(fn: (req: { url?: string }, res: unknown, next: () => void) => void): void;
      };
    }) {
      server.middlewares.use((req, _res, next) => {
        const url = req.url ?? '';
        const [path = '', query] = url.split('?', 2);
        if (/^\/play\/[^/]+\/$/.test(path)) {
          req.url = `${path}index.html${query === undefined ? '' : `?${query}`}`;
        }
        next();
      });
    },
  };
}

/** Reference pages that are single files at the root of `docs/`. */
const REFERENCE: { file: string; link: string }[] = [
  { file: 'glossary.md', link: '/glossary' },
  { file: 'troubleshooting.md', link: '/troubleshooting' },
];

export default defineConfig({
  title: 'Gameable Engine',
  description:
    'Gameable Engine: a browser game engine with gaussian-splat worlds on WebGPU, and game logic as a WebAssembly component.',
  lang: 'en-GB',
  cleanUrls: true,
  // Dead links are a bug, not a warning. Keep this false.
  ignoreDeadLinks: false,
  // The Gameable look is dark only (STYLE.md); no theme toggle.
  appearance: 'force-dark',
  vite: { plugins: [playIndexPlugin()] },
  head: [
    ['link', { rel: 'icon', type: 'image/png', href: '/brand/favicon.png' }],
    ['link', { rel: 'preconnect', href: 'https://fonts.googleapis.com' }],
    ['link', { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' }],
    [
      'link',
      {
        rel: 'stylesheet',
        href: 'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@500;600;700;800&display=swap',
      },
    ],
  ],
  themeConfig: {
    logo: '/brand/icon-mint.png',
    nav: [
      { text: 'Start', link: '/start/01-install' },
      { text: 'Play', link: '/play' },
      { text: 'Concepts', link: '/concepts/' },
      { text: 'Recipes', link: '/recipes/' },
      { text: 'three.js apps', link: '/three/gameable-character' },
      { text: 'API', link: '/api/' },
      {
        text: 'Reference',
        items: [
          { text: 'Glossary', link: '/glossary' },
          { text: 'Troubleshooting', link: '/troubleshooting' },
        ],
      },
    ],
    sidebar: [
      {
        text: 'Start',
        collapsed: false,
        items: [
          { text: 'Overview', link: '/' },
          { text: 'Play the examples', link: '/play' },
          ...itemsOf('start'),
        ],
      },
      { text: 'Concepts', collapsed: false, items: conceptItems() },
      { text: 'Recipes', collapsed: false, items: recipeItems() },
      // For apps outside the engine: an ordinary three.js scene with a studio character in it.
      { text: 'In your three.js app', collapsed: false, items: itemsOf('three') },
      { text: 'API reference', collapsed: true, items: apiItems() },
      {
        text: 'Reference',
        collapsed: false,
        items: REFERENCE.filter((r) => existsSync(join(DOCS, r.file))).map((r) => ({
          text: titleOf('.', r.file),
          link: r.link,
        })),
      },
    ],
    outline: [2, 3],
    search: { provider: 'local' },
  },
});
